//! The C boundary, end to end, through a real third-party plugin.
//!
//! Everything else about plugins is tested against types compiled into the test
//! binary and reached through a Rust trait object, where the boundary does not
//! exist. These tests go through `fasttiff-plugin-example`'s `extern "C"` entry
//! point and its function-pointer vtables, so they are the only ones that can
//! catch a mismatch between the two sides of the ABI — a reordered struct
//! field, a marshalling step that drops a value, a plane index computed
//! differently on each side.
//!
//! The oracle is exact. The example library's `Invert` is a copy of the
//! viewer's built-in `Invert`, so running both over the same stack must produce
//! *identical* results, down to the float bits and the result's name. A
//! comparison with no tolerance is only possible because the boundary is meant
//! to be lossless, which is the property worth pinning.
//!
//! # Why this lives in the plugin's crate, and why not `dlopen`
//!
//! Because `cargo test` does not build a `cdylib`. A test that could only reach
//! the plugin by loading a `.dll` would either skip (if nobody had run
//! `cargo build` first) or — far worse — pass against a **stale** artifact
//! built from different source, which is exactly what happened while these
//! tests were being written: a deliberately broken plugin kept the oracle
//! green. So the marshalling is tested through `library::register_from`, which
//! is the whole loader minus `dlopen`/`dlsym`, called with the query function
//! of a plugin cargo has *just rebuilt* — guaranteed, because that plugin is
//! this crate. `dlopen` itself gets a smoke test at the bottom, which skips
//! when the artifact is missing or older than its source; there is nothing in
//! those two library calls worth a false green.

#![cfg(not(target_arch = "wasm32"))]

use fast_tiff_viewer::plugins::{self, library, Origin, Registry};
use fasttiff_plugin_api::{
    Confidence, HostContext, ImageResult, ImportHost, ImportRequest, Importer, Outcome, ParamKind,
    ParamValue, Params, PixelType, Plane, PlaneData, Plugin, StackInfo, VolumeMode, VolumeView,
};
use std::path::{Path, PathBuf};

/// Load the example plugin through the ABI, without a shared library.
///
/// `ft_plugin_v1_query` is the same `#[no_mangle] extern "C"` function the
/// `.dll` exports; reaching it as a Rust path rather than through `dlsym`
/// changes how it is *found*, not how it is *called*.
fn example() -> library::Loaded {
    // SAFETY: the symbol is generated by `export_plugin!`, so it has exactly
    // the signature `FtQueryFn` names, and it is linked into this binary for
    // the whole run.
    unsafe {
        library::register_from(
            fasttiff_plugin_example::ft_plugin_v1_query,
            Path::new("fasttiff-plugin-example"),
        )
    }
    .expect("the example plugin should register")
}

/// One registered plugin, by id.
fn plugin(id: &str) -> library::LoadedPlugin {
    example()
        .plugins
        .into_iter()
        .find(|p| p.info().id == id)
        .unwrap_or_else(|| panic!("{id} should be registered"))
}

/// The registered importer.
fn importer() -> library::LoadedImporter {
    example().importers.remove(0)
}

fn volume() -> VolumeView {
    VolumeView {
        mode: VolumeMode::Mip,
        density: 1.0,
        iso: 0.5,
        eye: [0.0; 3],
        forward: [0.0, 0.0, 1.0],
        up: [0.0, 1.0, 0.0],
        right: [1.0, 0.0, 0.0],
    }
}

/// A small float stack whose planes are all different, so a mixed-up plane
/// index cannot pass unnoticed.
fn stack(channels: usize, frames: usize) -> fast_tiff_viewer::stack::Stack {
    let (w, h) = (5u32, 4u32);
    let n = (w * h) as usize;
    let mut planes = Vec::new();
    for t in 0..frames {
        for c in 0..channels {
            let base = (c * 1000 + t * 10) as f32;
            planes.push(PlaneData::F32(
                (0..n).map(|i| base + i as f32 * 0.5).collect(),
            ));
        }
    }
    let img = ImageResult {
        width: w,
        height: h,
        channels,
        slices: 1,
        frames,
        pixel_type: PixelType::F32,
        planes,
        channel_colors: Vec::new(),
        name: "oracle".into(),
    };
    plugins::to_stack(&img, None, false).expect("the fixture should open")
}

#[test]
fn the_library_registers_what_it_declares() {
    let loaded = example();

    let ids: Vec<String> = loaded.plugins.iter().map(|p| p.info().id.clone()).collect();
    assert_eq!(
        ids,
        vec![
            "dev.fasttiff.example.invert",
            "dev.fasttiff.example.showinfo",
            "dev.fasttiff.example.panics"
        ],
        "both plugins must register, in the order the macro lists them"
    );

    let importers: Vec<String> = loaded
        .importers
        .iter()
        .map(|i| i.info().id.clone())
        .collect();
    assert_eq!(importers, vec!["dev.fasttiff.example.raw"]);

    // Strings really crossed, rather than arriving empty or as the id again.
    let info = loaded.plugins[0].info();
    assert_eq!(info.name, "Invert (from library)");
    assert_eq!(info.menu_path, "Examples");
    assert!(!info.version.is_empty(), "the version did not cross");
    assert!(
        info.description.contains("shared library"),
        "the description did not cross: {:?}",
        info.description
    );

    // And the importer's file types, which the Open dialog is built from.
    let types = loaded.importers[0].file_types();
    assert_eq!(types.len(), 1);
    assert_eq!(types[0].description, "Raw binary image");
    assert_eq!(types[0].extensions, vec!["raw", "bin"]);
}

/// The point of the whole phase: the same filter, one side called as a Rust
/// trait and one side through the C vtable, must agree exactly.
#[test]
fn a_loaded_plugin_matches_the_built_in_it_was_copied_from() {
    let mut from_library = plugin("dev.fasttiff.example.invert");
    let mut built_in = plugins::builtin::Invert;

    for (channels, frames, all) in [(1usize, 1usize, false), (3, 2, true), (3, 2, false)] {
        let s = stack(channels, frames);
        let mut params = Params::new();
        params.set("all_channels", ParamValue::Bool(all));

        let view = plugins::describe_view(&s, frames - 1, false, volume());
        let mut host = plugins::StackHost::new(&s, view.clone());
        let want = built_in.run(&mut host, &params).expect("built-in run");

        let mut host = plugins::StackHost::new(&s, view);
        let got = from_library.run(&mut host, &params).expect("library run");

        let (Outcome::NewDocument(want), Outcome::NewDocument(got)) = (&want, &got) else {
            panic!("both should produce a document, got {want:?} / {got:?}");
        };
        assert_eq!(
            got, want,
            "the library's result differs from the built-in's for \
             {channels}c x {frames}t, all_channels={all}"
        );
        // Not vacuous: the fixture must actually have produced pixels, and the
        // `all_channels` flag must have crossed and been acted on.
        assert_eq!(want.planes.len(), if all { channels } else { 1 });
        assert_eq!(want.planes[0].len(), 20);
    }
}

#[test]
fn a_dialog_declared_inside_the_library_arrives_intact() {
    let from_library = plugin("dev.fasttiff.example.invert");

    // One channel: the plugin suppresses the checkbox, and that decision has to
    // survive the crossing too.
    let s = stack(1, 1);
    let host = plugins::StackHost::new(&s, plugins::describe_view(&s, 0, false, volume()));
    assert!(
        from_library.params(&host).is_empty(),
        "a single-channel stack should offer no controls"
    );

    let s = stack(3, 1);
    let host = plugins::StackHost::new(&s, plugins::describe_view(&s, 0, false, volume()));
    let decls = from_library.params(&host);
    assert_eq!(decls.len(), 1);
    assert_eq!(decls[0].key, "all_channels");
    assert_eq!(decls[0].label, "All channels");
    assert_eq!(decls[0].kind, ParamKind::Bool { default: false });
    assert!(
        decls[0]
            .help
            .as_deref()
            .unwrap_or("")
            .contains("every channel"),
        "the help text did not cross: {:?}",
        decls[0].help
    );
}

struct Silent;
impl ImportHost for Silent {
    fn progress(&mut self, _f: f32) -> bool {
        true
    }
    fn log(&mut self, _m: &str) {}
}

fn tmp(name: &str, bytes: &[u8]) -> PathBuf {
    let p = std::env::temp_dir().join(format!("fasttiff-boundary-{name}"));
    std::fs::write(&p, bytes).expect("write fixture");
    p
}

#[test]
fn an_importer_in_a_library_reads_a_file_end_to_end() {
    let mut raw = importer();

    // 4x4 u16, little-endian, values 0..16 — 32 bytes, so the dialog's square
    // guess should be 4.
    let bytes: Vec<u8> = (0u16..16).flat_map(|v| v.to_le_bytes()).collect();
    let file = tmp("import.raw", &bytes);

    assert_eq!(raw.probe(&file, &bytes), Confidence::Maybe);
    assert_eq!(
        raw.probe(Path::new("x.tif"), &[]),
        Confidence::No,
        "the importer must not claim files it does not handle"
    );

    // The dialog is declared from the *path*, so a default computed inside the
    // plugin from the file's size proves the path crossed correctly.
    let decls = raw.params(&file);
    let width = decls.iter().find(|d| d.key == "width").expect("width");
    assert_eq!(
        width.kind,
        ParamKind::Int {
            default: 4,
            min: 1,
            max: 1 << 20
        },
        "the guessed default did not cross"
    );
    let ty = decls.iter().find(|d| d.key == "type").expect("type");
    let ParamKind::Choice { default, options } = &ty.kind else {
        panic!("expected a choice, got {:?}", ty.kind);
    };
    assert_eq!(*default, 1);
    assert_eq!(options.len(), 4, "the option list did not cross whole");
    assert_eq!(options[3], "32-bit float");

    let mut params = Params::new();
    params.set("width", ParamValue::Int(4));
    params.set("height", ParamValue::Int(4));
    params.set("type", ParamValue::Choice(1));
    params.set("little_endian", ParamValue::Bool(true));
    let result = raw
        .import(
            &ImportRequest {
                path: file.clone(),
                params,
            },
            &mut Silent,
        )
        .expect("the import should succeed");

    assert_eq!((result.image.width, result.image.height), (4, 4));
    assert_eq!(result.image.pixel_type, PixelType::U16);
    assert_eq!(
        result.image.planes,
        vec![PlaneData::U16((0..16).collect())],
        "every sample must survive the crossing in order"
    );
    result.image.validate().expect("the shape must be valid");

    // And the host can turn it into an ordinary document.
    let s = plugins::to_stack(&result.image, result.info.as_ref(), false).expect("open");
    assert_eq!(s.dimensions(), Some((4, 4)));

    let _ = std::fs::remove_file(file);
}

/// Every parameter kind must survive the crossing, not just the two the other
/// tests happen to use — a marshalling mistake in one arm is otherwise
/// invisible until a plugin uses that arm.
#[test]
fn every_parameter_kind_crosses_in_both_directions() {
    let mut raw = importer();

    // 2x1 f32, big-endian, with a 3-byte header: only correct if the Int, the
    // Choice and both Bools all arrived intact.
    let mut bytes = vec![0xFFu8; 3];
    bytes.extend(1.5f32.to_be_bytes());
    bytes.extend((-2.25f32).to_be_bytes());
    let file = tmp("kinds.raw", &bytes);

    let mut params = Params::new();
    params.set("width", ParamValue::Int(2));
    params.set("height", ParamValue::Int(1));
    params.set("type", ParamValue::Choice(3)); // 32-bit float
    params.set("images", ParamValue::Int(1));
    params.set("offset", ParamValue::Int(3));
    params.set("little_endian", ParamValue::Bool(false));

    let result = raw
        .import(
            &ImportRequest {
                path: file.clone(),
                params,
            },
            &mut Silent,
        )
        .expect("import");
    assert_eq!(result.image.pixel_type, PixelType::F32);
    assert_eq!(result.image.planes, vec![PlaneData::F32(vec![1.5, -2.25])]);

    let _ = std::fs::remove_file(file);
}

/// A plugin that reports an error must reach the user as that error's own text,
/// not as a generic failure — the `last_error` half of the contract.
#[test]
fn an_error_raised_inside_the_library_keeps_its_message() {
    let mut raw = importer();
    let file = tmp("short.raw", &[0u8; 8]);

    let mut params = Params::new();
    params.set("width", ParamValue::Int(64));
    params.set("height", ParamValue::Int(64));
    params.set("type", ParamValue::Choice(1));
    let err = raw
        .import(
            &ImportRequest {
                path: file.clone(),
                params,
            },
            &mut Silent,
        )
        .expect_err("a short file must be refused");
    let msg = err.to_string();
    assert!(
        msg.contains("8192") && msg.contains("64x64"),
        "the plugin's own message did not cross: {msg}"
    );

    let _ = std::fs::remove_file(file);
}

/// The registry must not be able to tell where a plugin came from, except
/// through `Origin` — which is the whole design goal of the loader.
#[test]
fn loaded_plugins_join_the_same_registry_as_the_built_ins() {
    let loaded = example();

    let mut reg = Registry::new();
    let built_ins = reg.len();
    for p in loaded.plugins {
        assert!(reg.add(Box::new(p), Origin::Library));
    }
    for i in loaded.importers {
        assert!(reg.add_importer(Box::new(i), Origin::Library));
    }
    assert_eq!(reg.len(), built_ins + 3);
    assert!(
        reg.problems.is_empty(),
        "the example plugin should install cleanly: {:?}",
        reg.problems
    );

    let i = reg
        .find("dev.fasttiff.example.invert")
        .expect("the loaded plugin should be findable by id");
    assert_eq!(reg.entries()[i].origin, Origin::Library);

    // The Open dialog picks up the plugin's extensions.
    let types = reg.open_file_types();
    assert!(
        types
            .iter()
            .any(|t| t.extensions.contains(&"raw".to_string())),
        "the plugin's file type did not reach the Open dialog: {types:?}"
    );
    assert!(reg.claims_extension(Path::new("a.bin")));
}

/// Pixels read through the C boundary must be the same pixels, not merely
/// similar ones — the host-callback direction, which the oracle covers only
/// indirectly.
#[test]
fn planes_read_by_a_loaded_plugin_address_the_same_data_as_the_host() {
    let mut from_library = plugin("dev.fasttiff.example.invert");

    let s = stack(3, 2);
    // Frame 1, so a plugin that ignored `frame_index` and read frame 0 fails.
    let view = plugins::describe_view(&s, 1, false, volume());
    let mut host = plugins::StackHost::new(&s, view);

    let mut params = Params::new();
    params.set("all_channels", ParamValue::Bool(true));
    let Outcome::NewDocument(got) = from_library.run(&mut host, &params).expect("run") else {
        panic!("expected a document");
    };

    let mut host = plugins::StackHost::new(&s, plugins::describe_view(&s, 1, false, volume()));
    let mut buf = Vec::new();
    for c in 0..3 {
        host.read_plane_f32(Plane::new(c, 0, 1), &mut buf)
            .expect("read");
        let lo = buf.iter().cloned().fold(f32::INFINITY, f32::min);
        let hi = buf.iter().cloned().fold(f32::NEG_INFINITY, f32::max);
        let want: Vec<f32> = buf.iter().map(|&v| hi - (v - lo)).collect();
        assert_eq!(
            got.planes[c],
            PlaneData::F32(want),
            "channel {c} of frame 1 came back computed from different pixels"
        );
    }
}

/// The guarantee everything else rests on: a plugin that genuinely panics must
/// come back as an error, and the process must still be running to read it.
///
/// This is the only test that fires a real panic through the boundary. The host
/// cannot catch it — an `extern "C"` function aborts on unwind — so what is
/// under test is `export_plugin!`'s own guard, and the only way to test that is
/// to let a plugin built with the macro actually panic.
#[test]
fn a_plugin_that_really_panics_is_contained_and_reported() {
    let mut panics = plugin("dev.fasttiff.example.panics");

    let s = stack(1, 1);
    for choice in [0usize, 1] {
        let mut params = Params::new();
        params.set("where", ParamValue::Choice(choice));
        let mut host = plugins::StackHost::new(&s, plugins::describe_view(&s, 0, false, volume()));
        let err = panics
            .run(&mut host, &params)
            .expect_err("a panicking plugin must be an error, not a result");
        assert!(
            err.to_string().contains("panicked"),
            "the panic must be reported as one: {err}"
        );
        assert!(
            err.to_string().contains("on purpose"),
            "the plugin's own panic message should reach the user: {err}"
        );
    }

    // Still alive, and still able to run something else.
    let mut invert = plugin("dev.fasttiff.example.invert");
    let mut host = plugins::StackHost::new(&s, plugins::describe_view(&s, 0, false, volume()));
    assert!(
        matches!(
            invert.run(&mut host, &Params::new()),
            Ok(Outcome::NewDocument(_))
        ),
        "a panic in one plugin must not poison another"
    );
}

/// The metadata half of the boundary. Pixels crossing proves nothing about
/// whether the file's *scale* crossed, and a plugin that silently measures in
/// pixels while believing it is measuring in microns is worse than one that
/// fails.
#[test]
fn the_files_calibration_reaches_a_loaded_plugin() {
    let mut show = plugin("dev.fasttiff.example.showinfo");

    // A stack carrying every optional field, so a dropped one is visible.
    let s = stack(2, 1);
    let mut info = plugins::describe_stack(&s);
    info.unit = Some("micron".into());
    info.spacing = fasttiff_plugin_api::Spacing {
        x: Some(0.325),
        y: Some(0.325),
        z: Some(1.5),
    };
    info.frame_interval_s = Some(0.05);
    info.calibration = Some((-100.0, 2.5));
    info.channel_names = vec!["GFP".into(), "mCherry".into()];
    info.description = Some("ImageJ=1.54f\nunit=micron".into());
    info.mode = fasttiff_plugin_api::DisplayMode::Composite;

    let view = plugins::describe_view(&s, 0, false, volume());
    let mut host = plugins::StackHost::new(&s, view).with_info(info.clone());

    let Outcome::Message(report) = show.run(&mut host, &Params::new()).expect("run") else {
        panic!("Show Info should report a message");
    };

    // Each of these is `unknown`/`none` unless the value really crossed.
    assert!(report.contains("pixel: 0.325 x 0.325 micron"), "{report}");
    assert!(report.contains("z step: 1.5 micron"), "{report}");
    assert!(report.contains("frame interval: 0.05 s"), "{report}");
    assert!(report.contains("calibration: -100 + 2.5 * raw"), "{report}");
    assert!(report.contains("channels: GFP, mCherry"), "{report}");
    assert!(report.contains("mode: Composite"), "{report}");
    assert!(report.contains("description: 24 bytes"), "{report}");
    assert!(report.contains("2 channel(s)"), "{report}");

    // And the log line crossed too.
    assert!(
        host.messages.iter().any(|m| m.contains("metadata")),
        "the plugin's log line did not reach the host: {:?}",
        host.messages
    );
}

/// A stack that states nothing must read as "unknown", not as zero. A plugin
/// cannot tell a missing calibration from a zero one, so the boundary has to.
#[test]
fn absent_metadata_stays_absent_rather_than_becoming_zero() {
    let mut show = plugin("dev.fasttiff.example.showinfo");
    let s = stack(1, 1);
    let view = plugins::describe_view(&s, 0, false, volume());
    let mut host = plugins::StackHost::new(&s, view).with_info(StackInfo {
        name: "bare".into(),
        ..Default::default()
    });

    let Outcome::Message(report) = show.run(&mut host, &Params::new()).expect("run") else {
        panic!("expected a message");
    };
    assert!(report.contains("pixel: unknown x unknown"), "{report}");
    assert!(report.contains("z step: unknown"), "{report}");
    assert!(report.contains("frame interval: unknown"), "{report}");
    assert!(report.contains("calibration: none"), "{report}");
}

/// The same direction reversed: what an importer learned about a file has to
/// reach the document, or every measurement made on it afterwards is in the
/// wrong units.
#[test]
fn an_importers_metadata_reaches_the_document() {
    let mut raw = importer();
    let bytes: Vec<u8> = (0u16..16).flat_map(|v| v.to_le_bytes()).collect();
    let file = tmp("meta.raw", &bytes);

    let mut params = Params::new();
    params.set("width", ParamValue::Int(4));
    params.set("height", ParamValue::Int(4));
    params.set("type", ParamValue::Choice(1));
    params.set("pixel_size", ParamValue::Float(0.65));

    let result = raw
        .import(
            &ImportRequest {
                path: file.clone(),
                params,
            },
            &mut Silent,
        )
        .expect("import");

    let info = result.info.expect("the importer's metadata should cross");
    assert_eq!(info.spacing.x, Some(0.65));
    assert_eq!(info.spacing.y, Some(0.65));
    assert_eq!(info.unit.as_deref(), Some("micron"));
    assert!(
        info.description
            .as_deref()
            .unwrap_or("")
            .contains("raw import"),
        "{:?}",
        info.description
    );
    // The host fills these in, because it is the side that knows them.
    // The importer names it from the file stem, which tmp() prefixes.
    assert_eq!(info.name, "fasttiff-boundary-meta");
    assert_eq!(info.path.as_deref(), Some(file.to_string_lossy().as_ref()));

    // And it survives being turned into a real document.
    let s = plugins::to_stack(&result.image, Some(&info), false).expect("open");
    // Compared with a tolerance, not for equality: TIFF stores pixel size as
    // XResolution, a *rational*, so 0.65 goes to disk as 1/0.65 and comes back
    // as 0.6499999999999999. That is the file format, not the boundary — the
    // boundary is what the exact assertion on `info` above already checked.
    let close = |got: Option<f64>, want: f64| got.is_some_and(|v| (v - want).abs() < 1e-9);
    assert!(
        close(s.tiff.meta.pixel_width, 0.65) && close(s.tiff.meta.pixel_height, 0.65),
        "the spacing did not reach the written file: {:?} x {:?}",
        s.tiff.meta.pixel_width,
        s.tiff.meta.pixel_height
    );
    assert_eq!(s.tiff.meta.unit.as_deref(), Some("micron"));

    let _ = std::fs::remove_file(file);
}

/// An error from a plugin must read once, not twice. The plugin stores the
/// message and the host adds the framing; both doing it gave the user
/// "not applicable: not applicable: ...".
#[test]
fn an_error_is_framed_once_not_twice() {
    let mut raw = importer();
    let file = tmp("cancel.raw", &[0u8; 32]);

    struct Cancelled;
    impl ImportHost for Cancelled {
        fn progress(&mut self, _f: f32) -> bool {
            false
        }
        fn log(&mut self, _m: &str) {}
    }

    let mut params = Params::new();
    params.set("width", ParamValue::Int(4));
    params.set("height", ParamValue::Int(4));
    params.set("type", ParamValue::Choice(1));
    let err = raw
        .import(
            &ImportRequest {
                path: file.clone(),
                params,
            },
            &mut Cancelled,
        )
        .expect_err("a cancelled import must not succeed");

    // `Unsupported`'s Display prefix, exactly once.
    let msg = err.to_string();
    assert_eq!(msg, "not applicable: cancelled", "{msg}");
    assert_eq!(msg.matches("not applicable").count(), 1);

    let _ = std::fs::remove_file(file);
}

/// An importer's progress and log calls used to go nowhere: the host passed a
/// null table, so a long import could not be watched or stopped.
#[test]
fn an_importer_can_report_progress_and_be_stopped() {
    struct Watching {
        seen: Vec<f32>,
        logged: Vec<String>,
    }
    impl ImportHost for Watching {
        fn progress(&mut self, f: f32) -> bool {
            self.seen.push(f);
            true
        }
        fn log(&mut self, m: &str) {
            self.logged.push(m.to_string());
        }
    }

    let mut raw = importer();
    let bytes = vec![0u8; 4 * 4 * 2 * 3]; // three 4x4 u16 images
    let file = tmp("progress.raw", &bytes);

    let mut params = Params::new();
    params.set("width", ParamValue::Int(4));
    params.set("height", ParamValue::Int(4));
    params.set("type", ParamValue::Choice(1));
    params.set("images", ParamValue::Int(3));

    let mut host = Watching {
        seen: Vec::new(),
        logged: Vec::new(),
    };
    raw.import(
        &ImportRequest {
            path: file.clone(),
            params,
        },
        &mut host,
    )
    .expect("import");

    assert_eq!(
        host.seen,
        vec![0.0, 1.0 / 3.0, 2.0 / 3.0],
        "progress did not cross the boundary"
    );
    assert!(
        host.logged.iter().any(|m| m.contains("3 4x4")),
        "the importer's log did not cross: {:?}",
        host.logged
    );

    let _ = std::fs::remove_file(file);
}

// ------------------------------------------------------- the `dlopen` lane

/// Where the example library lands, derived from this test binary's own path so
/// that debug and release both work without being told which.
///
/// `None` when it has not been built, or when it is older than its source:
/// `cargo test` does not rebuild a `cdylib`, and a smoke test that silently
/// exercised last week's binary would be worse than no smoke test.
fn built_library() -> Option<PathBuf> {
    let exe = std::env::current_exe().ok()?;
    // .../target/<profile>/deps/plugin_library-<hash>.exe
    let path = exe.parent()?.parent()?.join(format!(
        "{}fasttiff_plugin_example.{}",
        if cfg!(target_os = "windows") {
            ""
        } else {
            "lib"
        },
        plugins::LIBRARY_EXT
    ));
    let built = std::fs::metadata(&path).ok()?.modified().ok()?;

    let src = Path::new(env!("CARGO_MANIFEST_DIR")).join("src/lib.rs");
    let edited = std::fs::metadata(src).ok()?.modified().ok()?;
    (built >= edited).then_some(path)
}

/// `dlopen` + `dlsym` + everything above: the one thing `register_from` cannot
/// cover. Skips rather than fails, because whether the artifact exists depends
/// on how cargo was invoked, not on whether the code is right.
#[test]
fn a_built_shared_library_loads_and_registers() {
    let Some(path) = built_library() else {
        eprintln!(
            "skipping the dlopen smoke test: no current \
             fasttiff_plugin_example.{} (run `cargo build -p fasttiff-plugin-example`)",
            plugins::LIBRARY_EXT
        );
        return;
    };
    let loaded = library::load_library(&path)
        .unwrap_or_else(|e| panic!("{} should load: {e}", path.display()));
    assert_eq!(loaded.plugins.len(), 3);
    assert_eq!(loaded.importers.len(), 1);
    assert_eq!(loaded.plugins[0].info().id, "dev.fasttiff.example.invert");
}

/// The path a user actually takes: put a library in the plugin folder, start
/// the app, and find it in the menu.
///
/// Everything above tests a plugin the test handed to the loader itself. This
/// tests *discovery* — the search path, the extension filter, and
/// `Registry::with_installed` — which is the half that was broken the first
/// time this feature was tried.
///
/// It sets `FASTTIFF_PLUGIN_PATH`, which is process-global. Safe here only
/// because no other test in this binary reads it; do not add one that does.
#[test]
fn a_library_in_the_plugin_folder_reaches_the_menu() {
    let Some(built) = built_library() else {
        eprintln!("skipping discovery test: no current example library");
        return;
    };

    let dir = std::env::temp_dir().join("fasttiff-plugin-discovery-test");
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir).expect("create plugin dir");
    let installed = dir.join(built.file_name().expect("file name"));
    std::fs::copy(&built, &installed).expect("copy the library");
    // A file with the right extension that is not a library, and one with the
    // wrong extension: the scan must report the first and ignore the second.
    std::fs::write(
        dir.join(format!("broken.{}", plugins::LIBRARY_EXT)),
        b"junk",
    )
    .unwrap();
    std::fs::write(dir.join("notes.txt"), b"not a plugin").unwrap();

    std::env::set_var(plugins::discover::PLUGIN_PATH_VAR, &dir);
    assert!(
        plugins::search_paths().contains(&dir),
        "the override should come first on the search path"
    );

    let reg = Registry::with_installed();
    std::env::remove_var(plugins::discover::PLUGIN_PATH_VAR);

    assert!(
        reg.find("dev.fasttiff.example.invert").is_some(),
        "a library in the plugin folder should reach the menu; problems: {:?}",
        reg.problems
    );
    assert!(
        reg.claims_extension(Path::new("scan.raw")),
        "its importer should reach the Open dialog"
    );
    // The junk file is reported, by name, rather than silently skipped.
    assert!(
        reg.problems.iter().any(|p| p.contains("broken.")),
        "the unloadable file should be reported: {:?}",
        reg.problems
    );
    assert!(
        !reg.problems.iter().any(|p| p.contains("notes.txt")),
        "a non-library must not be treated as a failed plugin: {:?}",
        reg.problems
    );

    let _ = std::fs::remove_dir_all(&dir);
}

/// Loading something that is not a plugin must be a message, not a crash.
#[test]
fn a_file_that_is_not_a_plugin_is_reported_rather_than_loaded() {
    let junk = tmp(&format!("junk.{}", plugins::LIBRARY_EXT), b"not a library");
    let err = library::load_library(&junk).expect_err("junk must not load");
    assert!(
        err.contains("could not load") || err.contains("ft_plugin_v1_query"),
        "unhelpful message: {err}"
    );
    let _ = std::fs::remove_file(junk);
}

/// A real, loadable binary with no plugin entry point — the plugin folder will
/// eventually contain one — must be turned away by the missing symbol.
#[test]
fn a_real_binary_without_the_entry_point_is_rejected_by_symbol() {
    let not_a_plugin = std::env::current_exe().expect("current exe");
    match library::load_library(&not_a_plugin) {
        Ok(_) => panic!("the test binary is not a plugin and must not load as one"),
        Err(e) => assert!(
            e.contains("could not load") || e.contains("ft_plugin_v1_query"),
            "unhelpful message: {e}"
        ),
    }
}
