//! The plugin end to end, through the C boundary, on a synthetic recording.
//!
//! The fixture is a movie where the left half brightens after one stimulus and
//! the right half after the other. Nothing else in it changes. So the answer is
//! unambiguous: the first channel must be bright on the left and dark on the
//! right, the second the other way round, and getting the epoch arithmetic
//! wrong by even one step swaps them.
//!
//! It goes through `library::register_from` rather than calling the plugin
//! directly, because half of what is being tested is that the timing crosses
//! the boundary at all — the trigger comes out of tag 270, and tag 270 reaches
//! the plugin through the host's callbacks.

use fast_tiff_viewer::plugins::{self, library};
use fasttiff_plugin_api::{
    ImageResult, Outcome, ParamValue, Params, PixelType, PlaneData, Plugin, StackInfo, VolumeMode,
    VolumeView,
};

const W: u32 = 12;
const H: u32 = 8;
const FRAMES: usize = 200;
const DURATION_S: f64 = 20.0;
const TRIGGER_S: f64 = 1.0;
const STEP_S: f64 = 2.0;
const RESP_S: f64 = 0.5;

/// The acquisition record, in the shape FastTIFF writes for a converted OIR.
fn description() -> String {
    format!(
        concat!(
            "ImageJ=1.54f\nimages={f}\nframes={f}\nfinterval=0.1\n",
            "\"[Dimensions]\"\t\"\"\n",
            "\"T Dimension\"\t\"{f}, 0.000 - {d:.3} [s], Interval FreeRun\"\n",
            "\"[Event 1]\"\t\"\"\n",
            "\"Event Contents\"\t\"DRS\"\n",
            "\"Event Timer\"\t\"{ms:.6}[ms]\"\n",
        ),
        f = FRAMES,
        d = DURATION_S,
        ms = TRIGGER_S * 1000.0,
    )
}

/// A movie in which the left half responds to step 0 and the right half to
/// step 1, in every epoch.
///
/// The response is a ramp rather than a step, because the plugin measures a
/// *derivative*: a single-frame jump would be a spike the Gaussian smooths
/// away, and a plateau has no derivative at all.
fn movie() -> Vec<PlaneData> {
    let spf = DURATION_S / FRAMES as f64;
    (0..FRAMES)
        .map(|t| {
            let now = t as f64 * spf;
            // Where are we relative to the stimulation pattern?
            let since = now - TRIGGER_S;
            let mut left = 0f32;
            let mut right = 0f32;
            if since >= 0.0 {
                let in_epoch = since % (STEP_S * 2.0);
                // A rise over the response window after each step's onset.
                if (0.0..RESP_S).contains(&in_epoch) {
                    left = (in_epoch / RESP_S) as f32 * 100.0;
                }
                if (STEP_S..STEP_S + RESP_S).contains(&in_epoch) {
                    right = ((in_epoch - STEP_S) / RESP_S) as f32 * 100.0;
                }
            }
            let mut px = vec![10f32; (W * H) as usize];
            for y in 0..H as usize {
                for x in 0..W as usize {
                    px[y * W as usize + x] += if x < W as usize / 2 { left } else { right };
                }
            }
            PlaneData::F32(px)
        })
        .collect()
}

fn stack() -> fast_tiff_viewer::stack::Stack {
    let img = ImageResult {
        width: W,
        height: H,
        channels: 1,
        slices: 1,
        frames: FRAMES,
        pixel_type: PixelType::F32,
        planes: movie(),
        channel_colors: Vec::new(),
        name: "synthetic".into(),
    };
    let info = StackInfo {
        name: "synthetic".into(),
        description: Some(description()),
        ..Default::default()
    };
    plugins::to_stack(&img, Some(&info), false).expect("the fixture should open")
}

fn volume() -> VolumeView {
    VolumeView {
        mode: VolumeMode::Mip,
        density: 1.0,
        iso: 0.5,
        eye: [0.0; 3],
        forward: [0.0, 0.0, 1.0],
        up: [0.0, 1.0, 0.0],
        right: [1.0, 0.0, 0.0],
    }
}

fn plugin() -> library::LoadedPlugin {
    // SAFETY: the symbol is generated by `export_plugin!`, so it has the
    // signature `FtQueryFn` names, and is linked into this binary for the run.
    let mut loaded = unsafe {
        library::register_from(
            fasttiff_plugin_derivatives::ft_plugin_v1_query,
            std::path::Path::new("fasttiff-plugin-derivatives"),
        )
    }
    .expect("the plugin should register");
    loaded.plugins.remove(0)
}

fn params() -> Params {
    let mut p = Params::new();
    p.set("pattern", ParamValue::Text("10,01".into()));
    p.set("step_duration", ParamValue::Float(STEP_S));
    p.set("resp_duration", ParamValue::Float(RESP_S));
    p.set("trig_number", ParamValue::Int(1));
    p.set("start_from_epoch", ParamValue::Int(1));
    p.set("frame_lag", ParamValue::Int(-1));
    p.set("sync_coef", ParamValue::Float(-0.003));
    p.set("sigma", ParamValue::Float(2.3));
    p.set("channel", ParamValue::Int(0));
    p
}

fn run() -> (ImageResult, Vec<String>) {
    let s = stack();
    let view = plugins::describe_view(&s, 0, false, volume());
    let mut host = plugins::StackHost::new(&s, view);
    let out = plugin()
        .run(&mut host, &params())
        .expect("the plugin should run");
    let Outcome::NewDocument(img) = out else {
        panic!("expected a document, got {out:?}");
    };
    (*img, host.messages.clone())
}

/// The mean of one half of a channel.
fn half(img: &ImageResult, channel: usize, left: bool) -> f32 {
    let PlaneData::F32(px) = &img.planes[channel] else {
        panic!("expected f32 planes")
    };
    let mut sum = 0f32;
    let mut n = 0;
    for y in 0..H as usize {
        for x in 0..W as usize {
            let is_left = x < W as usize / 2;
            // Skip the two columns either side of the seam: the spatial blur
            // crosses it, and the test is about which half responded.
            if x.abs_diff(W as usize / 2) < 3 {
                continue;
            }
            if is_left == left {
                sum += px[y * W as usize + x];
                n += 1;
            }
        }
    }
    sum / n as f32
}

#[test]
fn each_stimulus_lands_in_its_own_channel() {
    let (img, _) = run();
    assert_eq!(img.channels, 2, "one channel per firing step");
    assert_eq!(img.planes.len(), 2);
    assert_eq!((img.width, img.height), (W, H));
    assert_eq!(
        (img.slices, img.frames),
        (1, 1),
        "the result is one plane deep"
    );

    let (c0_left, c0_right) = (half(&img, 0, true), half(&img, 0, false));
    let (c1_left, c1_right) = (half(&img, 1, true), half(&img, 1, false));

    assert!(
        c0_left > c0_right * 5.0,
        "the first stimulus should have responded on the left: {c0_left} vs {c0_right}"
    );
    assert!(
        c1_right > c1_left * 5.0,
        "the second stimulus should have responded on the right: {c1_right} vs {c1_left}"
    );
    // Not vacuous: something actually responded.
    assert!(c0_left > 1.0, "no response at all in the first channel");
    assert!(c1_right > 1.0, "no response at all in the second channel");
}

/// The overlay only reads as an overlay if the colours cross the boundary.
#[test]
fn the_channels_come_back_magenta_and_green() {
    let (img, _) = run();
    assert_eq!(
        img.channel_colors,
        vec![[255, 0, 255], [0, 255, 0]],
        "the overlay colours did not survive the crossing"
    );

    // And they survive being written into a document, which is where they turn
    // into the LUTs the display reads.
    let s = plugins::to_stack(&img, None, false).expect("open the result");
    assert_eq!(s.display.dims.channels, 2);
    let luts: Vec<[u8; 3]> = s.display.luts.iter().map(|l| l[255]).collect();
    assert_eq!(
        luts,
        vec![[255, 0, 255], [0, 255, 0]],
        "the written file's channel LUTs are not magenta and green"
    );
}

/// The epoch count is derived from the recording, not asked for.
#[test]
fn the_number_of_epochs_is_the_number_that_fit() {
    let (_, log) = run();
    let line = log
        .iter()
        .find(|m| m.contains("epoch(s)"))
        .expect("the plugin should say what it did");
    // Trigger at 1 s, epochs of 4 s, last step 2 s in plus a 0.5 s window,
    // inside 20 s * 0.997 = 19.94 s: 1 + 4e + 2.5 <= 19.94 gives e <= 4.11,
    // and epochs 1..=4 is four of them.
    assert!(
        line.contains("4 epoch(s)"),
        "expected four epochs to fit: {line}"
    );
}

/// Without the acquisition record there is no trigger, and guessing one would
/// produce a confident map of an arbitrary moment.
#[test]
fn a_file_without_the_timing_is_refused_with_a_reason() {
    let s = stack();
    let view = plugins::describe_view(&s, 0, false, volume());

    for (desc, want) in [
        ("", "duration"),
        ("ImageJ=1.54f\nimages=200\nframes=200\n", "duration"),
        (
            "\"T Dimension\"\t\"200, 0.000 - 20.000 [s]\"\n",
            "event marker",
        ),
    ] {
        let mut host = plugins::StackHost::new(&s, view.clone()).with_info(StackInfo {
            name: "bare".into(),
            description: Some(desc.to_string()),
            ..Default::default()
        });
        let err = plugin()
            .run(&mut host, &params())
            .expect_err("without timing there is nothing to do");
        assert!(
            err.to_string().contains(want),
            "{desc:?} gave {err}, expected something about {want:?}"
        );
    }
}

/// A response window shorter than two frames cannot be differentiated, and
/// says so rather than returning a map of nothing.
#[test]
fn too_short_a_response_window_is_refused() {
    let s = stack();
    let view = plugins::describe_view(&s, 0, false, volume());
    let mut host = plugins::StackHost::new(&s, view);
    let mut p = params();
    // 0.05 s at 0.1 s per frame is zero frames.
    p.set("resp_duration", ParamValue::Float(0.05));
    let err = plugin()
        .run(&mut host, &p)
        .expect_err("a sub-frame window cannot be differentiated");
    assert!(
        err.to_string().contains("at least 2"),
        "the message should say what is wrong: {err}"
    );
}
