//! Cross-validation against independently-produced TIFFs: the committed
//! fixtures under `tests/fixtures/` were written by **tifffile** (`tff_`, the
//! scientific-Python reference writer) and **Pillow** (`pil_`, whose
//! compressed path runs the actual libtiff encoders). Decoding them proves
//! the reader against other producers' output — not just our own writer's.
//!
//! Fixtures are generated by `tests/fixtures/generate_fixtures.py` (committed
//! alongside; rerun it to regenerate). Pixel values are pure functions of the
//! flat sample index, so expectations are recomputed here — THE FORMULAS MUST
//! MATCH THE GENERATOR:
//!
//!     u8 : (g*7 + 13) % 256
//!     i8 : that - 128        (reads back as the u8 value, widened)
//!     u16: (g*131 + 17) % 65536
//!     i16: that - 32768      (reads back as the u16 value)
//!     u32: (g*97 + 5) % 100000
//!     i32: that - 50000
//!     f32: (g % 2000) * 0.25 - 250.0
//!
//! Filename grammar: `{gen}_{dtype}_spp{s}_p{pages}_{info}.tif`; prefix
//! `err_` = the file must fail to open, `ij_` = ImageJ metadata checks.

use fast_tiff_lib::{
    read_frame_f32, read_frame_u16, read_frame_u8, read_plane_f32, read_plane_u16, read_plane_u8,
    DisplayMode, TiffStack,
};
use std::path::{Path, PathBuf};

const W: usize = 23;
const H: usize = 11;

/// The u8 formula; `i8` fixtures read back as exactly these values too (the
/// reader's sign-bit flip undoes the generator's `- 128`).
fn expect_u8(g: u64) -> u8 {
    ((g * 7 + 13) % 256) as u8
}

/// The u16 formula; `i16` fixtures read back as exactly these values (the
/// reader's `^ 0x8000` display offset undoes the generator's `- 32768`).
fn expect_u16(g: u64) -> u16 {
    ((g * 131 + 17) % 65536) as u16
}

/// 8-bit sources widen onto 0..65535 in the u16 display path.
fn widen(b: u8) -> u16 {
    ((b as u16) << 8) | b as u16
}

fn expect_u32_as_f32(g: u64) -> f32 {
    ((g * 97 + 5) % 100000) as f32
}

fn expect_i32_as_f32(g: u64) -> f32 {
    ((g * 97 + 5) % 100000) as f32 - 50000.0
}

fn expect_f32(g: u64) -> f32 {
    ((g % 2000) as f32) * 0.25 - 250.0
}

fn fixtures_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests").join("fixtures")
}

/// Verify every page of one fixture against the formula for `dtype`.
fn check_pixels(stack: &TiffStack, dtype: &str, spp: usize, pages: usize, name: &str) {
    assert_eq!(stack.frames.len(), pages, "{name}: page count");
    let frame_samples = (W * H * spp) as u64;
    for (p, frame) in stack.frames.iter().enumerate() {
        let base = p as u64 * frame_samples;
        // For chunky multi-sample frames the readers deinterleave per plane;
        // plane `pl`'s i-th value is global sample index base + i*spp + pl.
        let planes: usize = if spp > 1 { spp } else { 1 };
        for pl in 0..planes {
            let n_pixels = W * H;
            let g_of = |i: usize| base + (i * spp + pl) as u64;
            match dtype {
                "u8" => {
                    let got: Vec<u8> = if spp > 1 {
                        read_plane_u8(&stack.mmap, frame, stack.byte_order, pl).unwrap()
                    } else {
                        read_frame_u8(&stack.mmap, frame, stack.byte_order).unwrap().into_owned()
                    };
                    let want: Vec<u8> = (0..n_pixels).map(|i| expect_u8(g_of(i))).collect();
                    assert_eq!(got, want, "{name}: page {p} plane {pl}");
                }
                "i8" => {
                    let got = read_frame_u16(&stack.mmap, frame, stack.byte_order, None).unwrap();
                    let want: Vec<u16> = (0..n_pixels).map(|i| widen(expect_u8(g_of(i)))).collect();
                    assert_eq!(got.as_ref(), &want[..], "{name}: page {p}");
                }
                "u16" | "i16" => {
                    let got: Vec<u16> = if spp > 1 {
                        read_plane_u16(&stack.mmap, frame, stack.byte_order, None, pl).unwrap()
                    } else {
                        read_frame_u16(&stack.mmap, frame, stack.byte_order, None).unwrap().into_owned()
                    };
                    let want: Vec<u16> = (0..n_pixels).map(|i| expect_u16(g_of(i))).collect();
                    assert_eq!(got, want, "{name}: page {p} plane {pl}");
                }
                "u32" | "i32" | "f32" => {
                    let got: Vec<f32> = if spp > 1 {
                        read_plane_f32(&stack.mmap, frame, stack.byte_order, pl).unwrap()
                    } else {
                        read_frame_f32(&stack.mmap, frame, stack.byte_order).unwrap().into_owned()
                    };
                    let f = match dtype {
                        "u32" => expect_u32_as_f32,
                        "i32" => expect_i32_as_f32,
                        _ => expect_f32,
                    };
                    let want: Vec<f32> = (0..n_pixels).map(|i| f(g_of(i))).collect();
                    assert_eq!(got, want, "{name}: page {p} plane {pl}");
                }
                other => panic!("{name}: unknown dtype token {other:?}"),
            }
        }
    }
}

#[test]
fn every_fixture_decodes_correctly() {
    let dir = fixtures_dir();
    let mut names: Vec<String> = std::fs::read_dir(&dir)
        .unwrap_or_else(|e| panic!("fixtures dir {} missing: {e}", dir.display()))
        .filter_map(|e| e.ok())
        .map(|e| e.file_name().to_string_lossy().into_owned())
        .filter(|n| n.ends_with(".tif"))
        .collect();
    names.sort();
    // Guard against a silently-empty directory looking like a green run.
    assert!(
        names.len() >= 25,
        "expected the full fixture matrix, found only {} .tif files — rerun \
         tests/fixtures/generate_fixtures.py",
        names.len()
    );

    for name in &names {
        let path = dir.join(name);
        // `{gen}_{dtype}_spp{s}_p{pages}_...` — parse the contract tokens.
        let tokens: Vec<&str> = name.trim_end_matches(".tif").split('_').collect();
        let (gen, dtype) = (tokens[0], tokens[1]);
        let spp: usize = tokens[2].strip_prefix("spp").unwrap().parse().unwrap();
        let pages: usize = tokens[3].strip_prefix('p').unwrap().parse().unwrap();

        if gen == "err" {
            assert!(
                TiffStack::open(&path).is_err(),
                "{name}: unsupported layout must be refused with an error"
            );
            continue;
        }

        let stack = TiffStack::open(&path)
            .unwrap_or_else(|e| panic!("{name}: failed to open: {e:#}"));
        check_pixels(&stack, dtype, spp, pages, name);

        if gen == "ij" {
            // Written by tifffile's imagej mode — an independent producer of
            // the ImageJ description (2 channels x 3 time frames, composite).
            let meta = &stack.meta;
            assert_eq!(meta.channels, 2, "{name}: channels");
            assert_eq!(meta.slices, 1, "{name}: slices");
            assert_eq!(meta.frames, 3, "{name}: frames");
            assert_eq!(meta.mode, DisplayMode::Composite, "{name}: mode");
            assert_eq!(meta.unit.as_deref(), Some("um"), "{name}: unit");
            assert_eq!(meta.fps, Some(10.0), "{name}: fps");
            assert_eq!(meta.spacing, Some(0.5), "{name}: spacing");
            assert_eq!(meta.loop_playback, Some(false), "{name}: loop");
            assert!(
                stack.description.as_deref().is_some_and(|d| d.contains("ImageJ=")),
                "{name}: raw description exposed"
            );
        }
    }
}
